export const CREATE_REPORT_REQUEST="CREATE_REPORT_REQUEST"
export const CREATE_REPORT_SUCCESS="CREATE_REPORT_SUCCESS"
export const CREATE_REPORT_FAIL="CREATE_REPORT_FAIL"
export const CREATE_REPORT_RESET="CREATE_REPORT_RESET"


export const GET_REPORT_REQUEST="GET_REPORT_REQUEST"
export const GET_REPORT_SUCCESS="GET_REPORT_SUCCESS"
export const GET_REPORT_FAIL="GET_REPORT_FAIL"

export const DELETE_REPORT_REQUEST="DELETE_REPORT_REQUEST"
export const DELETE_REPORT_SUCCESS="DELETE_REPORT_SUCCESS"
export const DELETE_REPORT_FAIL="DELETE_REPORT_FAIL"
export const DELETE_REPORT_RESET="DELETE_REPORT_RESET"

//for error handle
export const CLEAR_ERRORS="CLEAR_ERRORS"